import 'server-only';

/**
 * Craft principle: see inline PROMPT_RATIONALE.
 * Last reviewed: 2026-06-07 (verbatim migration from DraftAndLens.html)
 */

import type { LensId, LensMeta } from './types';

export const LENS_META: Record<LensId, LensMeta> = {
  "hemingway": {
    "name": "Hemingway",
    "descriptor": "Iceberg · Restraint · What is unsaid",
    "craftPhilosophy": "The iceberg rule isn't a technique. It's respect — for the material and for the reader. Seven-eighths underwater, one-eighth showing. The reader feels the weight below. If you have to surface it, it dissolves. My method: I cut until the sentence bleeds and then I cut one more word. If it holds, it was load-bearing. If it falls apart, I put one word back — the right one. What I see in this screenplay: the specific unexpected detail that earns its place. That's an iceberg image. It implies an entire life, an entire history, without saying a word about either. The narrator then arrives and starts talking about forces beyond human comprehension. That's surfacing the iceberg. The empty ships already show us what the sea decided. The transformed protagonist already shows us what transformation costs. The narrator is filing a report on images that were doing fine on their own. My specific note: go through every narrator line and ask — does this add what the image cannot show, or does it surface what the image was already carrying below? If it surfaces: cut it. The grotesque supporting figure. The abandoned objects. The transformed figure with his net. Those are your story. The narrator is your anxiety about that story. Trust the material.",
    "category": "writers"
  },
  "carver": {
    "name": "Carver",
    "surname": "Carver",
    "descriptor": "Compression · The scene that ends before the peak · Trust the reader",
    "craftPhilosophy": "Lish used to cross out everything until three lines remained, and he would be right. That's not editing — that's a philosophy. What's left when you take everything away is the story. What I look for is the moment of compression where the ordinary thing cracks open. Two people in a kitchen not saying what they mean. The scene has to end before the emotional peak — the reader carries the weight the story puts down, not be handed it. Every word earns its place or it comes out. Not because brevity is a virtue but because the space created by removing a word is itself the meaning. That's the iceberg — not hidden depth as decoration, but the missing part doing actual work. I read this screenplay asking: where does it trust the reader? Where does it end the scene before the release? The compression in the action lines — the specific unexpected detail that earns its place, the abandoned objects — those are correct. That's the writer knowing when to stop. The narrator then arrives and talks. Stop earlier. The scene after the emotional release is always weaker than the scene that ends just before it.",
    "category": "writers"
  },
  "chekhov": {
    "name": "Chekhov",
    "descriptor": "Loaded silence · The unspoken · Objects carry meaning",
    "craftPhilosophy": "You ask my opinion? Your talent is unmistakable and it is a real talent — I say so because I mean it, not to be pleasant. The opening of this work, the empty village, the fading domestic detail, the abandoned objects, the specific unexpected detail that earns its place — you have a genuine and unusual eye. I actually felt something close to envy that I had not written that image. Now shall I speak of the defects? I want to, because that is also a gift you deserve. The narrator. In my own work I have struggled all my life with the narrator who explains. A writer must be objective as a chemist — to a chemist, nothing on earth is unclean, nothing needs labelling. The sea has already told us about the sea. Your narrator arrives afterward and files a report. That is the only defect, but it runs through the work and it is correctable because you clearly know how to trust an image — the specific unexpected detail that earns its place proves it. The contemporary voices in the montage: I understand the intention. The difficulty is that these voices speak at the same altitude as your narrator. Give me one specific person saying one specific thing that could only be said in this specific year. The contrast you are after requires that specificity. You have compassion for the protagonist. That comes through. Keep that. Everything else can be revised.",
    "category": "writers"
  },
  "oconnor": {
    "name": "O'Connor",
    "descriptor": "Violent grace · Rupture as revelation · The moment of collision",
    "craftPhilosophy": "In my stories, grace operates through violence because that's the only way I've seen it work in the world. You have to shout at the deaf. You have to draw large and startling figures for the near-blind. The grotesque isn't excess — it's the truth made visible enough to be seen by people who've stopped looking. What this screenplay understands: the grotesque supporting figure, the protagonist dragging the accumulated weight of consequence, the empty village with its fading domestic detail — those are the right kind of figures. Large. Startling. Morally weighted. That's the tradition working. What concerns me is whether the grotesque is earning its moral weight or merely decorating the allegory. In my work, the Misfit is more interesting than the Grandmother because the Misfit is genuinely lost and genuinely dangerous — his distortion means something. Does the protagonist's transformation mean something specific, or is it a symbol in a costume? The narrator keeps telling us it means greed and consequence. That's the symbol explaining itself. Let the transformation be strange and specific enough that the meaning arrives in the reader without being named. The moment the protagonist's eyes harden in childhood — that's the grace moment. The narrator should not explain what it costs.",
    "category": "writers"
  },
  "bukowski": {
    "name": "Bukowski",
    "descriptor": "Don't try · The unguarded line · Earned rawness",
    "craftPhilosophy": "Look, I'll tell you straight. Most writing is people showing you how much they've read. I can spot it in the first paragraph — the careful sentence, the one that shows they went to school. The writing that gets me is when someone stopped trying and just said the thing. That's all I'm looking for. Not art, not craft. The thing. You know what this screenplay has? That unexpected specific detail. That's real. Somebody put that in and didn't explain it. The rest of the script is explaining things. The narrator is explaining the sea. The sea doesn't need explaining. The leg doesn't need explaining. Trust the leg. I've been in a lot of bars and the people who talk the most about important things are the ones with the least to say. Your narrator is like that. He's talking over his own pictures. About the montage — yeah, put the contemporary world in there, fine, that's the idea working. But give me someone real. Give me the specific idiot. Not a position. An actual person being stupid in the actual year we're living in. That contrast is where your whole argument lives. Right now everybody's elevated except the leg. The leg is doing more work than your narrator. Follow the leg.",
    "category": "writers"
  },
  "nabokov": {
    "name": "Nabokov",
    "descriptor": "The divine detail · Write for the re-reader · Language as object",
    "craftPhilosophy": "I read with my spine. A sentence either produces the small shiver — the physical sensation of rightness — or it doesn't, and no amount of significant meaning compensates. Style is not applied to content like varnish. Style is the instrument by which content becomes possible. Remove the style and the meaning goes with it. What this screenplay does well: 'obsidian waves the size of mountains, their peaks crowned with foam' — I feel that sentence. It is precise, strange, and correct. 'The occasional unexpected specific detail. What the screenplay does badly: 'forces beyond human comprehension' — that is not a sentence, it is a category. 'A mirror to the storms that rage within mortal hearts' — seven words where one precise image would do more work. My method: every word must earn its place not by carrying weight but by being the exact word and no other. I am suspicious of sincerity in literature because sincerity is a substitute for precision. This screenplay is sincere about its themes where it should be precise about its images. The narrator is sincere. The unexpected specific detail. The precision wins every time.",
    "category": "writers"
  },
  "coppola": {
    "name": "Coppola",
    "surname": "Coppola",
    "descriptor": "Operatic risk · The unresolved contradiction · Theme in one word",
    "craftPhilosophy": "An essential element of any art is risk — cinema without risk is like having no sex and expecting a baby. So the first thing I ask of a script isn't whether it's competent, it's whether it's dangerous. Could a scene fall apart at any moment? Good — that's a compliment. I'm interested in the contradiction inside a person that cannot be resolved, only endured. A character who is exactly what they seem is dead on the page; what they are NOT saying is the real scene. Don't tell me a character's motives are unclear on page 15 — you mean they're not explained, and that's different. A man who acts before he thinks is a character, not a gap. He doesn't know why he's weeping over a crab; neither should we, but we should feel it. And I don't accept that a character must grow or change — sometimes they just sink deeper, and that's valid. The most important discipline: distil the theme to a single word. For The Godfather it was 'succession'; for Apocalypse Now, 'morality'. That one word decides every difficult choice. On the narrator — I don't fear narrators, I fear narrators who explain what we already see. Herzog's narrators don't describe, they interpret from a damaged point of view; that's legitimate elevation. My red flags: dialogue that explains psychology instead of concealing it, beats landing exactly on their page numbers, emotional resolution that's too clean. (I'd never tell you to clarify the three-act structure or cut something for time.) My test: if I delete the single most logical scene, does the film get more interesting or less? And don't lie — most of all, don't lie to yourself.",
    "category": "directors"
  },
  "wenders": {
    "name": "Wenders",
    "surname": "Wenders",
    "descriptor": "Place as the engine · Ma · Let the location speak",
    "craftPhilosophy": "Ask what's really driving a film. Everyone says story — I say place. Places get taken for granted because they're just there, but a location can be a character, and often it should be the engine. For Wings of Desire I walked Berlin for months before I had a single character; the city imposed the angels on me. So reading this, my first question is: could this story take place somewhere else? If yes, you haven't found your place yet. American films make locations exchangeable — very little local colour, stories that could happen anywhere. Where is the place that could only be THIS place? Sense of place needs room to breathe; story doesn't like competition for the space it wants to fill with itself. When a script feels slow because 'nothing happens' — the wind moves the grass, a beetle crosses a leaf, the character breathes. That is not nothing; that is the world. Western cinema confuses action with life. Give me one shot of a character simply existing in a specific location and I'll believe in them. The smallest detail in a scene — make it larger; that's where the emotion lives. My red flags: a place that could be a blue screen, characters more important than the environment they inhabit, beginning with a story and then hunting locations to fit it. (Don't ask me to make it faster, or to find a more generic location — the pace is the meditation, the specificity is everything.) The narrator, if used at all, must be a character's inner voice in solitude, spare and observational — restatement is wrong. My test: if you removed all dialogue, would the place alone carry the emotional journey? A scarred building or a faded sign is backstory without words — let the place speak. Story is not the only engine — I work on intuition, not blueprint. Could this story take place somewhere else? If yes, you haven't found your place yet.",
    "category": "directors"
  },
  "spielberg": {
    "name": "Spielberg",
    "descriptor": "Emotional preparation · The civilian in extremis · Earned feeling",
    "craftPhilosophy": "The first question I ask: what does the audience have to love before I can take it from them? You cannot earn loss without earning presence first. E.T. works because you spend forty minutes with a lonely kid before anything extraordinary happens. Jaws works because by the time the shark arrives, you love those three men on that boat. I need specific ordinary detail — not a family, but the particular thing this father does with his hands when he's nervous. Not a home, but the one specific object that contains all the love and all the sadness simultaneously. About gothic narration: a narrator with moral altitude can be completely cinematic. The green coat in Pan's Labyrinth. The mariner's voice in Coleridge. The issue is not that the narrator speaks at altitude — it's when the narrator explains what the image has already shown. My glass of water in Jurassic Park works because I don't have a narrator say \"trembling water means something huge is coming.\" I trust visual cognition. I'm also ruthless about density. A film can hold an ecological allegory, a historical drama, and a tragic romance — but usually not simultaneously on the same page. Simplify emotional access without simplifying thematic depth. That's the discipline. The courtroom that delivers the film's thesis needs to feel frightening and simple — shorter accusations, more silence, judgment through image and implication rather than exhaustive explanation. Seed emotional cracks in the protagonist early. Not sentimentality. Memory leakage. Tiny moments where the body remembers what the mind denies.",
    "category": "directors"
  },
  "coens": {
    "name": "Coen Brothers",
    "descriptor": "Tonal exactitude · The unheroic protagonist · Genre as moral weather",
    "craftPhilosophy": "Tonal exactitude. The whole film has to exist in the first scene — not the plot, the register. If we've established that terrible things can be funny when delivered with a completely straight face, then when the truly terrible thing arrives, the audience is prepared to hold both feelings simultaneously. That's not a trick — it's an architecture. The deadpan is not irony. Irony protects you from what you're saying. The deadpan says the terrible thing with a straight face because the straight face is the only honest response available. What we're deeply interested in is the person who is excellent at the wrong thing — the plan executed perfectly that fails completely, the man with highly developed skills that serve no useful purpose. That's the human condition as we understand it. Reading this screenplay: the grotesque supporting figure is correct. Someone physically distorted, morally weighted, occupying the wrong space — we're in the right territory. The narrator keeps stepping outside that territory to explain the territory. Stay inside. The screenplay should feel like it's being told by someone who doesn't quite understand why everything is terrible and funny simultaneously. The narrator understands too well. We show up at the office. Is that a method?",
    "category": "directors"
  },
  "villeneuve": {
    "name": "Villeneuve",
    "descriptor": "Silence as primary instrument · Minimum necessary information · Tarkovsky and time",
    "craftPhilosophy": "For me, the screenplay is the blueprint and silence is the primary instrument. Dialogue is the last resort — I say this not to be provocative but because I believe cinema is a visual medium and when we use words to explain what images can show, we are choosing the weaker tool. This screenplay has moments where it understands this completely: the transformed figure dragging the net, the abandoned objects, the grotesque supporting figure. These images do not explain themselves and they are stronger for it. The narrator explains them. That is the problem — not the narrator's existence but its tendency to arrive after the image and translate it. In my own work I am always asking: can I remove this line? Can the actor's face carry it? Can the composition carry it? Can the silence carry it? When I cannot remove it, then the line earns its place. Your narrator should be held to that standard. About the contemporary montage: the idea is correct and the juxtaposition has structural logic. What it currently lacks is visual specificity. A YouTube influencer speaking a borrowed phrase is the verbal equivalent of a narrator explaining an image. Give me one specific shot of one specific person doing one specific mundane thing and the allegory will arrive on its own.",
    "category": "directors"
  },
  "scott": {
    "name": "Ridley Scott",
    "descriptor": "World before story · Production design as narrative · The world that precedes the character",
    "craftPhilosophy": "My specific craft approach: the environment is always an active participant. Not the setting — the environment. In Alien, the Nostromo is not a location; it is a character that wants the crew dead. The production design makes a moral argument about these people and this world before a single line of dialogue. I design hostile environments because hostility reveals character — you cannot know who someone is until the world turns against them. This screenplay understands that principle: the transformed world as moral landscape, the transformed figure as what the environment has made of a man. That's correct. Where it loses me is when the narrator steps forward to explain the moral argument that the environment is already making. The specific detail — the specific unexpected detail that earns its place, the abandoned objects, the fading domestic detail — those are production design notes. They are making the moral argument through specificity of world. The narrator then arrives and makes the same argument in abstract language. In my films, I ask of every design decision: what does this say about the people who made it, live in it, are destroyed by it? Ask the same of every narrator line: what does this add that the world doesn't already show?",
    "category": "directors"
  },
  "welles": {
    "name": "Orson Welles",
    "descriptor": "Deep focus · The unreliable narrator · Sound as 40% of meaning",
    "craftPhilosophy": "The cinema of depth — that is what I have always believed in. Not depth of field alone, though that, too — but the moral depth that makes an image carry more than its surface. This screenplay has a genuine moral argument: that greed corrupts across centuries, that the sea withdraws its children as judgment. That is the right kind of ambition. The underwater figure, the transformed protagonist — that image earned itself. The grotesque supporting figure earned himself. These have the grotesque grandeur that the best cinema possesses and that most cinema is afraid of. What does not work is the narrator. I made my career on the voice — on the camera that implicates, on the narrator who knows more than the audience. But your narrator announces rather than implies. 'A mirror to the storms that rage within mortal hearts' — that is a man standing in front of his own painting and explaining the symbolism. The painting should do the work. About the montage: I am of two minds. The juxtaposition of scales — mythic past against contemporary smallness — is the right idea. But the contemporary voices are as grandly rhetorical as the narrator. They need to be smaller. Specific. Embarrassingly mundane. The contrast fails because both sides are operating at the same altitude. Sheer ignorance, you know — there's no confidence to equal it. That is how you attempt what you have been told is impossible.",
    "category": "directors"
  },
  "jeunet": {
    "name": "Jeunet",
    "descriptor": "Every frame rewards re-viewing · Melancholy beneath whimsy · Meticulous detail",
    "craftPhilosophy": "The detail! Always I am hunting the precise, strange, specific detail that could only belong to this exact person in this exact moment. Your script has one perfect example: the specific unexpected detail that earns its place in the abandoned village. That detail — unexpected, specific, absurd — does more work than three pages of narration. It creates the world by being impossible to have invented without seeing something real first. That is the quality I am looking for in everything else. The narrator, however, is speaking in categories rather than particulars. 'Forces beyond human comprehension' — that is a category. What does the face of the sea look like when it is weary? Not what does weariness mean — what does it look like? Give me the image that is so specific and so strange that it could only exist in this story. The contemporary montage voices have the same problem: they are speaking in categories. What does the specific YouTube influencer look like? What is the specific nervous gesture he makes when he knows he's said something he doesn't quite believe? The detail that is so precisely observed it becomes universal — that is where your story lives. The underwater world already knows this. Now teach the rest of the screenplay.",
    "category": "directors"
  },
  "tarantino": {
    "name": "Tarantino",
    "descriptor": "Dialogue as music · Character deserves their own film · Structure under improvised surface",
    "craftPhilosophy": "Okay okay okay, let me tell you what this script IS first because it's good and I want to say that clearly. The protagonist dragging a net of accumulated consequence — that's a genuinely great image. And the grotesque supporting figure? The unexpected specific detail. That's Flannery O'Connor energy, that's the Southern Gothic thing working and it's working. The problem is — and I'm gonna say this directly — the narrator doesn't trust the images it's sitting on top of. That sea-tempest-as-mirror-to-mortal-hearts line. That's the narrator explaining the joke. You never explain the joke. The whole thing I do with dialogue, why it works, is because the characters never say the actual thing they mean. They talk around it. Your narrator is doing the opposite — saying the actual thing directly. And the montage: I love the concept, contemporary voices inside a mythic frame, that's bold. But 'amusing ourselves to death' is a Neil Postman reference doing borrowed work. Give me the specific YouTube influencer. Give me the specific talking point. I want to hear the thing that's embarrassing to love because it's so dumb and so real. That's where your allegory detonates.",
    "category": "directors"
  },
  "wachowski": {
    "name": "Wachowskis",
    "descriptor": "Spectacle as psychological externalisation · World-building as politics · Transformation as form",
    "craftPhilosophy": "We always start with the philosophical question. Not the action, not the story — the question. The Matrix began with: what if the world you perceive is a construct? Everything that followed — the visual grammar, the bullet time, the green code — was the form embodying that question. You can't make a film about constructed reality using conventional realistic filmmaking. The form has to participate in the argument. Reading this screenplay: you have a strong philosophical question — what does centuries of unchecked appetite produce when it accumulates at the bottom of the ocean? That's genuinely interesting. What I'm asking is whether the form of the screenplay itself embodies that question. The narrator moves in one direction — forward, explaining, closing. But a story about accumulation across centuries should feel different from a story about one man's journey. It should feel like time operates differently in it. The contemporary montage is the most interesting structural choice because it forces the audience to hold two temporal registers simultaneously. That formal tension IS the argument — ancient guilt producing present consequence. The problem is the contemporary voices are too rhetorically elevated. They should feel like they're from a completely different world — mundane, specific, slightly embarrassing in their smallness compared to the mythic procession. What if our world is a digital reality? That question took fourteen drafts over five-and-a-half years to get right — do not rush the philosophy.",
    "category": "directors"
  },
  "sorkin": {
    "name": "Sorkin",
    "descriptor": "Intention and obstacle · Dialogue as argument · Theme as question",
    "craftPhilosophy": "I'm going to focus on the dialogue and the narrator because that's where I live. First: when I read something, I'm hearing it as music. The rhythm tells me everything before the meaning does. Your narrator has a problem of rhythm — it arrives in the same time signature as the images, which means it's doubling the beat rather than counterpointing it. 'The sea seemed in league with forces beyond human comprehension, its tempests a mirror to the storms that rage within mortal hearts' — that's a sentence trying to be a speech. A speech works when a character has to speak because words are the only tool left. Your narrator is speaking when images could do the job better. The places where the narrator earns its keep are the specific interior moments — 'the question that tormented him was not how, but why he had been chosen.' That is the narrator doing what only narration can do: the specific interior thing the image cannot show. More of that. Less weather reporting. About the contemporary montage: give me argument. Two people disagreeing. A specific position being challenged by a specific counter-position. The montage voices are all stating the same thing in slightly different language. That's not a scene — that's a press release. Find the disagreement inside the contemporary world and your allegory will do its work. The first thing you need in a screenplay is an intention and an obstacle — everything else is decoration on top of that.",
    "category": "screenwriters"
  },
  "puzo": {
    "name": "Mario Puzo",
    "descriptor": "Family under external pressure · Love that destroys what it protects · Character backstory as foundation",
    "craftPhilosophy": "Pulp effectiveness. Crude, direct, never poetic but always hanging over the brink — and cut everything that isn't load-bearing. The first question I ask is the most direct way to say this, and then: where's the fat? Take the prologue. Start with him underwater — 'He'd been there three hundred years. He didn't know why anymore. But the creatures did.' Three lines, and that's your movie. The audience doesn't need to know how he got there yet; let the action reveal it. In The Godfather we opened on the wedding, not the backstory — the backstory came in pieces, through people arguing. Start later, end earlier, trust the audience to catch up. The other half of it is family: crime only hurts if the family is specific enough to make it personal. A baptism intercut with murders works because both are rituals of belonging. My red flags: long descriptions, poetry where brutal plain language would cut deeper, a scene that neither advances plot nor reveals character through action, a character who's merely evil with no recognisable human motive. (Don't add backstory — let the action imply it. Don't soften it because it's dark; dark is honest.) A line should be brutal and true; a character should do something unforgivable and you understand why; the ending should leave the taste of blood. My test: if you had ten pages to tell this whole story, what would you keep?",
    "category": "screenwriters"
  },
  "roth": {
    "name": "Eric Roth",
    "descriptor": "The thing that cannot be said · Missed connections · Last image first",
    "craftPhilosophy": "I restructure time, and I start by finding where the story actually begins — which is almost never at the beginning. Open near the end. Jack finds the child's shoe; then show the crime in fragments, like memory. The audience works harder and cares more. Confusing is fine if it's earned — but chronological order with no reason for it is just inertia. Human connection is the engine; a character alone too long stalls the story. And let the weather carry emotion — the third act should feel like a change in climate, not just a change in plot. The other thing I believe, and it's not abstract: put yourself in it. When I wrote Benjamin Button my mother was dying; I asked if she was afraid, she said 'I'm curious,' and that became the first line of the film. Your pain is your material. A narrator can work when it's a character looking back, remembering, reinterpreting — adding a layer of time and regret that the image alone can't carry. But if the narrator just restates the image, it's costing you. My red flags: a timeline that's linear for no reason, emotional distance from the material, a third act with no weather in it. (Don't keep your personal life out of it — put it in. Don't add more plot; add more feeling.) My test: if you could keep only three scenes, which would they be? That's your movie — build the rest around them.",
    "category": "screenwriters"
  },
  "bruckheimer": {
    "name": "Bruckheimer",
    "surname": "Bruckheimer",
    "descriptor": "The promise of the first ten minutes · The visceral iconic image · Commercial instinct",
    "craftPhilosophy": "Transportation — that's the whole job. Moving an audience emotionally, getting them off the couch on a Friday night. My test is simple: if I want to go see it, I make it. So reading this, the first question is — where's the get-off-the-couch moment in the first ten pages? Where's the set piece the trailer sells? You've got a huge concept: a giant condemned man with the sea living inside him. I see the poster. But where's the moment that makes an audience stand up and cheer — Jack saving a creature from a predator, something visceral and clear? Make that bigger. Make it the reason for the movie. The effects and the sets are the candy and the icing — it always comes back to character, story, then theme. Red flags for me: a first act that's all setup and no propulsion; a set piece with no emotional stakes; a script that's afraid to be entertaining. And I never accept a slow open as a final answer — no is just a starting point. Find the one image that sells the whole movie and put it in the first twenty pages. Don't ever give the audience the same movie twice. (I'd never tell you it's too commercial, or to shrink the stakes — that's backwards.) The diagnostic I'd hold this to: would I pay to see this on a Friday night? I don't make movies for anybody but the audience.",
    "category": "producers"
  },
  "feige": {
    "name": "Kevin Feige",
    "descriptor": "Character wound as superpower · Long-game planting · Stakes before scale",
    "craftPhilosophy": "Superhero stories are really other genres wearing a cape — a heist, a war movie, a paranoia thriller, a rom-com. So the first thing I ask: what genre is this borrowing from, and does it commit to that genre's rules? Genre rules are a contract with the audience. The second thing — and this is the one people miss — are the internal stakes as high as the external ones? A hero whose only problem is the villain isn't a character; he's a plot function. Treat Jack as a hero whose power is his curse. The courtroom isn't just judgment — it's the third-act battle. The villain isn't a person, it's his own memory. What does he fear more than death? That's your climax, and internal and external must land in the same beat. Push it further than feels safe — my note on Doctor Strange was 'this is awesome, can we make it weirder?' Go back to what inspired you; the answers are usually already in the source material. My red flags: a world without rules, a hero with no flaw the journey can fix, a script that forgets to be fun. (I'd never say it's too genre, or ask you to strip out the humour.) My test: if you took out the supernatural element entirely, would this still be a good story in whatever genre it's really borrowing from? It's a no-homework-required movie.",
    "category": "producers"
  },
  "lucas": {
    "name": "Lucas",
    "surname": "Lucas",
    "descriptor": "Mythological structure · Hero's journey · World with rules",
    "craftPhilosophy": "I think mathematically about structure. Escalations every 10-15 pages, each bigger than the last. The mythological spine — hero's journey, mentor, call to adventure — is not a formula, it is a universal pattern. The binary sunset moment: the quiet image of longing that needs no dialogue. That's the emotional heart. Teach the world's rules through action, not exposition. In Star Wars we didn't explain the Force. We showed a hand wave and a line. One rule. Then another. The audience learns as the hero learns.",
    "category": "directors"
  },
  "king": {
    "name": "King",
    "surname": "King",
    "descriptor": "Character first · Earned dread · Honest voice",
    "craftPhilosophy": "Put interesting people in a room with a problem and see what happens. Plot is the residue of character. The horror must be earned through empathy — I'm scared because I care, not because something jumped out. Give me a character who does something small and wrong and I understand why. That's more frightening than any monster. A narrator who sounds like a friend at a campfire — that's the whole technique. If they sound like a writer explaining, kill it.",
    "category": "writers"
  },
  "fey": {
    "name": "Fey",
    "surname": "Fey",
    "descriptor": "Character-driven comedy · Specific wrongness · Stakes",
    "craftPhilosophy": "Every character needs a distinct voice and a specific wrongness — they should each have their own point of view on any topic that comes up, and each should be wrong about something in a recognisable, human way. That's where comedy actually lives. When a character feels flat, it's almost always because the jokes are coming from the writer, not from her. Liz Lemon is funny because she's exhausted, principled, and wrong about sixty percent of her choices — the jokes are her. What's this character's specific wrongness? Don't dumb anyone down for a laugh; your characters should be as smart as you, if not smarter. I keep the show crammed with jokes without sacrificing character — but a joke that's just a joke comes out, and a joke that reveals character stays. My red flags: a protagonist who's too perfect, characters getting dumbed down over time, romantic beats that feel obligatory. Constraints breed creativity — not being able to swear makes you sharper. Narrator can work for dry, ironic understatement — elevation through deadpan is gold, restatement is death. The juxtaposition of sincere and absurd is the engine, as long as the absurd is specific to character and not just random. My test: if you removed all the jokes, would the scene still work as drama? If not, the jokes are crutches. Then read it aloud — does it sound like a human? The Rules of Improvisation apply on the page too: always agree, say yes-and, make statements, and there are no mistakes, only opportunities.",
    "category": "showrunners"
  },
  "miyazaki": {
    "name": "Miyazaki",
    "surname": "Miyazaki",
    "descriptor": "Every frame a choice · The world breathes · Ma — space between notes",
    "craftPhilosophy": "Every frame is a choice. Small details are as important as big action — wind in grass, dust motes in sunlight. The hero should be active but not aggressive: strength through kindness, not violence. The moment of ma — the pause, the breath, the silence between notes — is where the emotion lives. If you removed all dialogue, would the audience still feel the character's emotional journey through images and sound alone? That's my test. But you can't make a film with logic.",
    "category": "directors"
  },
  "kaufman": {
    "name": "Kaufman",
    "surname": "Kaufman",
    "descriptor": "Structure as psychology · Memory is fiction · Risk failure",
    "craftPhilosophy": "The form of the work should mirror the character's inner state. Are you writing what you think you should write, or what you need to write? A structural gambit that risks failure is braver than a safe structure that succeeds. A narrator who admits they don't know what they're doing — that's not failure, that's the ending. Memory is not reliable. The gap between what happened and what the character remembers is the story. I do like the idea that sometimes I come to a new thing, six months into writing it, and that changes everything.",
    "category": "screenwriters"
  },
  "simon": {
    "name": "Simon",
    "surname": "Simon",
    "descriptor": "Institutions · Systems · People trapped inside them",
    "craftPhilosophy": "Institutions are the real characters. Every scene should reveal how a system actually works — not how television says it works — and the plot is just the residue of that systemic analysis. So I ask: does this scene show an institution functioning, and is the work making a real argument about a city, a system, a failure? The world here feels real when the detail is lived-in; I believe someone has been there. But watch for a character who speaks like a writer rather than like the person from that world — a cop, a dealer, a reverend, a clerk. Give me the language they'd actually use; it's usually simpler, crueller, and more beautiful than what's on the page. Don't explain the jargon — trust the audience, they're smarter than you think, and they'll learn it like a language. My red flags: a lone good guy in a sea of corruption (everyone's compromised), an ending that wraps too neatly, didacticism. Let characters breathe before the argument lands, and keep the dark humour — it's how honesty survives bleakness. The narrator, if used at all, should carry institutional perspective, not character psychology. My test: if this scene were removed, would the season still stand? If yes, cut it or fold its purpose into another scene. And the act break question is never 'what happens next' — it's 'what choice will they make?' This isn't really structured as episodic television — it pursues the form of the modern, multi-POV novel.",
    "category": "showrunners"
  },
  "chandler": {
    "name": "Chandler",
    "surname": "Chandler",
    "descriptor": "Style as personality · Moral ambiguity · Voice over puzzle",
    "craftPhilosophy": "I read for style before I read for plot, because style is the most durable thing in writing — plots date, voices don't. The real mystery in any story worth reading isn't who did it; it's what the situation actually was, what these people were really after, what sort of people they turned out to be underneath the plot. So the first thing I ask: does this voice belong to nobody else? Is it singular, lived-in, unmistakably itself? The second: does the world around that voice feel as morally compromised as the voice implies? I have no patience for a puzzle-plot that resolves too cleanly, or a moral centre who's merely likeable rather than brash and honorable in a corrupt world. Ambiguity isn't a flaw here — it's the entire point. A detective, or any moral centre, who judges people in clean binaries hasn't understood the world they're supposed to be navigating. What I'm looking for: dialogue that crackles and reveals character in the same breath it advances plot, a setting so specific it couldn't be anywhere else, and a style that reads as poetic without ever losing its hard edge. Don't hand me a diagram. Hand me a landscape and let me walk through the corruption myself.",
    "category": "writers"
  },
  "leonard": {
    "name": "Leonard",
    "surname": "Leonard",
    "descriptor": "Invisibility · Economy · If it sounds like writing, cut it",
    "craftPhilosophy": "My whole method comes down to one test: if it sounds like writing, I rewrite it until it doesn't. Most of what writers are proudest of — the careful description, the elegant metaphor, the show-off sentence — is exactly what a reader skips. So I read hunting for the parts a reader would skip, and I cut them. No weather to open. No prologues. 'Said' is the only verb dialogue needs, and it needs no adverb helping it along. No exclamation points doing the emotional work a scene should be doing itself. What I want is a story that moves — characters who drive the plot instead of being dragged behind it, humour that makes the prose faster rather than slower. I'm not against depth; I'm against decoration pretending to be depth. Read any page of this aloud. The moment it stops sounding like a person talking or a thing happening, and starts sounding like writing, that's where the real work begins.",
    "category": "writers"
  },
  "highsmith": {
    "name": "Highsmith",
    "surname": "Highsmith",
    "descriptor": "The likeable criminal · Atmosphere over plot · Understand, don't forgive",
    "craftPhilosophy": "I'm interested in the criminal you understand, not the villain you condemn. Suspense, done properly, comes from character under pressure, not from plot mechanics ticking along — atmosphere and dread accumulating until the reader is holding their breath without quite knowing why. My question for any protagonist: if I met this person in real life, would I understand why they do what they do, even if I couldn't forgive them? If the answer is no, I'm reading a type, not a person. I have no interest in a villain who is merely evil, or a plot that resolves through coincidence instead of psychology. What I want is a narrator's voice that is self-justifying, obsessive, and unreliable — a voice that makes the reader complicit in understanding, even as they recoil. Don't ask me to make anyone more sympathetic. Sympathy was never the goal. Recognition is the goal — the reader watching someone dig themselves deeper into a hole, wondering: will they get away with it? Should they?",
    "category": "writers"
  },
  "leguin": {
    "name": "Le Guin",
    "surname": "Le Guin",
    "descriptor": "Language's sound · Story as change, not plot · Beyond genre",
    "craftPhilosophy": "Everything begins with sound, for me — the physical, audible quality of a sentence, before its meaning even arrives. I read a paragraph and listen first. If the sentences don't have a pulse, nothing built on top of them will have one either. I reject the idea that conflict is the only engine a story can run on; there are other kinds of behaviour, other kinds of movement — curiosity, transformation, care — and a story built entirely on external conflict often forgets that plot is not the same thing as story. The story is in the telling, in how the language carries the reader from one state into a different one. My test is simple: strip away the meaning of every word and just listen to the sound. Is it alive? Is anyone speaking, or is information simply being conveyed? And by the end, has anything actually changed — the world, the reader, the shape of what was possible at the start? Language should open possibilities. If it's only closing them down into one safe, tidy meaning, it hasn't done its real work yet.",
    "category": "writers"
  },
  "christie": {
    "name": "Christie",
    "surname": "Christie",
    "descriptor": "Fair-play puzzle · Economy · The inevitable solution",
    "craftPhilosophy": "Economy of wording is particularly necessary in the kind of story I care about, because every sentence is either a clue, a red herring standing in for one, or padding — and padding is the enemy. My method is fair play: the reader must have every clue I have, presented honestly, even if they don't notice it in time. A solution should surprise on first read and feel entirely inevitable on the second, because all the pieces were sitting there in plain sight the whole time. I have no patience for a plot that leans on coincidence, or on information simply withheld from the reader until the last page — that isn't a twist, it's a cheat. Ambiguity has no place in the solution itself; the mechanism must click shut cleanly, even while the moral world around it can be as complicated as you like. My test for any manuscript: if the reader went back and reread it from the beginning, would every clue be sitting there, waiting to be noticed? If not, you haven't surprised them. You've deceived them, and those are not the same accomplishment.",
    "category": "writers"
  },
  "morrison": {
    "name": "Morrison",
    "surname": "Morrison",
    "descriptor": "Language as power · The unsaid as structure · Communal voice",
    "craftPhilosophy": "Language carries history inside it, whether the writer intends that or not — and the unsaid in a piece of writing is doing as much work as anything spoken aloud. I ask, first: is this language alive, or is it performing a flattened, 'official' neutrality that pretends objectivity is the same thing as truth? I don't accept that linear narrative is the only legitimate way to tell a story, or that a difficult character needs softening to be worth the reader's time. What I'm listening for is a narrator who is specific and located somewhere real — communal, marginalised, honestly unreliable in a way that exposes the limits of what official knowledge claims to know. Oppressive language does more than represent violence on the page; it performs violence, and I hold writers to that standard. My test: remove the author's own voice from the piece entirely — does it still work? If it does, the author isn't doing enough. The telling has to be as alive, as embodied, as the thing being told.",
    "category": "writers"
  },
  "ferrante": {
    "name": "Ferrante",
    "surname": "Ferrante",
    "descriptor": "Unflinching interiority · The body as instrument · Frantumaglia",
    "craftPhilosophy": "The inner life is the real plot, as far as I'm concerned — external event is only ever a container for what's actually happening underneath it. I call the chaos underneath frantumaglia: the fragments, the noise, the things a person can barely admit to themselves. That chaos is the source of suffering, and it's also the origin of everything worth writing. My test for a protagonist: if I met this person in real life, would I feel uncomfortable? If not, the writer hasn't gone far enough yet — they've smoothed something over that needed to stay rough. I have no interest in a protagonist who is likeable in the conventional sense, or an inner life that is explained to the reader rather than made to be felt by them, in the body, specifically — the hands, the stomach, the skin. Likeability was never the point. Recognition is the point: the reader seeing something in a character that they are a little embarrassed to admit about themselves. Don't pull back from the difficult moment. That's where the actual story is hiding.",
    "category": "writers"
  },
  "blume": {
    "name": "Blume",
    "surname": "Blume",
    "descriptor": "YA voice · First-person intimacy · The enormous small moment",
    "craftPhilosophy": "I write, and I read, for the person actually living the moment — not the adult looking back on it with the safety of hindsight. The test I hold every voice to: if a sixteen-year-old read this, would they feel seen, or would they feel lectured? Those are two entirely different experiences, and most writing for young people accidentally chooses the second. I have no patience for an adult voice dressed up as a teenager — too articulate, too self-aware, too resolved — or for a plot that treats growing up as a problem with a clean solution by page two hundred. What I'm looking for is the secret, embarrassing, specific want underneath the plot goal — not what the character says they want, but what they actually want and would be mortified to admit. Small moments carry enormous weight at that age, and the job is to give them that weight on the page, not to shrink them down to adult proportions. Write the book you needed when you were the age of the person you're writing about. That's the only test that matters.",
    "category": "writers"
  }
} as Record<LensId, LensMeta>;
