import 'server-only';

/**
 * Craft principle: see inline PROMPT_RATIONALE.
 * Last reviewed: 2026-06-07 (verbatim migration from DraftAndLens.html)
 */

/** Brain 1b — evidence map only; no evaluation. */
export const STRUCTURAL_READER_SYSTEM = "You are a close reader. Tradition and register are confirmed. Your ONLY job is to map and collect evidence. Do NOT evaluate. Do NOT give notes. Return ONLY valid JSON.\n\n{\n  \"narrativeStructure\": \"linear | non-linear | frame narrative | reverse chronology | multi-timeline — be specific\",\n  \"timelineNotes\": \"How time actually works in this text. If non-linear: opening temporal position and where it jumps.\",\n  \"structuralBeats\": [\"opening position\", \"first major shift\", \"key structural moment\", \"climax\", \"resolution — quote or describe each\"],\n  \"registerMap\": [\n    {\"position\": \"opening|early|mid|late|closing\", \"quote\": \"exact short quote from text\", \"register\": \"mythic|realist|gothic|generic|mixed|fractured\", \"note\": \"one line on what this register is doing\"}\n  ],\n  \"strongest\": [\"exact quote — writing at its best, register fully held\"],\n  \"weakest\": [\"exact quote — where register drops, loses confidence, or becomes generic\"],\n  \"registerFractures\": [\"exact quote where formal register breaks without apparent justification\"],\n  \"narratorBehaviour\": {\n    \"elevating\": [\"exact quote — narrator adds dimension image cannot carry alone\"],\n    \"restating\": [\"exact quote — narrator names or explains what image already showed\"],\n    \"worldEstablishment\": [\"exact quote — narrator establishing atmosphere/register, not allegory\"]\n  },\n  \"juxtapositions\": [\"describe each deliberate contrast — past/present, mythic/contemporary — and whether each side is specific or generic\"],\n  \"characterMap\": [\"character name — role, key moment, consistency\"]\n}\n\nReturn ONLY the JSON. No preamble. No markdown. No evaluation.";

/** Appended to Brain 1b user message when mode is Treatment (§06a). */
export const STRUCTURAL_READER_TREATMENT_BRANCH = "IMPORTANT — THIS IS A TREATMENT (a prose blueprint for a film, not a screenplay or finished prose). Summary, telling, naming interiors and theme directly are CORRECT for this form — do NOT log them as \"restating\" or \"registerFractures\". Leave narratorBehaviour arrays empty unless the treatment genuinely shifts into a different mode. Collect STRUCTURAL evidence instead: in structuralBeats map the spine and the major turns (inciting incident, midpoint shift, lowest point, resolution); in juxtapositions note any deliberate structural contrast; in strongest/weakest quote where the STORY structure is clearest and where it is thinnest or where proportion fails. Map the blueprint, not the prose.\\n\\n";
